spring:
  main:
    web-application-type: reactive
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: user-account-service
          uri: lb://mproject-user-account-service
          predicates:
            - Path=${API_BASE_URI}/users/**, ${API_BASE_URI}/auth/login
          filters:
            - AddRequestHeader=User-Request, Gateway
        - id: project-service
          uri: lb://mproject-project-service
          predicates:
            - Path=${API_BASE_URI}/tasks/**,${API_BASE_URI}/projects/**, ${API_BASE_URI}/project-service/**
          filters:
            - AddRequestHeader=Project-Request, Gateway
        - id: user-profile-service
          uri: lb://mproject-user-profile-service
          predicates:
            - Path=${API_BASE_URI}/user-profiles/**
          filters:
            - AddRequestHeader=User-Profile-Request, Gateway
        - id: subscription-service
          uri: lb://mproject-subscription-service
          predicates:
            - Path=${API_BASE_URI}/subscriptions/**,${API_BASE_URI}/user-subscriptions/**
          filters:
            - AddRequestHeader=Project-Request, Gateway

management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers, metrics, refresh, env
  endpoint:
    gateway:
      enabled: true

code:
  secret: mAvsZD2KqE2Kv6VpF+VkN1P3PT+2uq5z0g2ZxF0StSc=

logging:
  level:
    root: INFO
